export const SET_NICKNAME = '[CHARACTER] SET_NICKNAME';
export const SET_GAME_MODE = '[CHARACTER] SET_GAME_MODE';
export const SET_SIDE = '[CHARACTER] SET_SIDE';
export const SET_PLAYER = '[CHARACTER] SET_PLAYER';
export const RESTORE_SESSION = '[CHARACTER] RESTORE_SESSION';
